# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ver_lay_list_ordini = QtWidgets.QVBoxLayout()
        self.ver_lay_list_ordini.setObjectName("ver_lay_list_ordini")
        self.ordini_label = QtWidgets.QLabel(self.centralwidget)
        self.ordini_label.setObjectName("ordini_label")
        self.ver_lay_list_ordini.addWidget(self.ordini_label)
        self.list_ordini = QtWidgets.QListWidget(self.centralwidget)
        self.list_ordini.setObjectName("list_ordini")
        self.ver_lay_list_ordini.addWidget(self.list_ordini)
        self.horizontalLayout_2.addLayout(self.ver_lay_list_ordini)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.ver_lay_list_articoli = QtWidgets.QVBoxLayout()
        self.ver_lay_list_articoli.setObjectName("ver_lay_list_articoli")
        self.articoli_label = QtWidgets.QLabel(self.centralwidget)
        self.articoli_label.setObjectName("articoli_label")
        self.ver_lay_list_articoli.addWidget(self.articoli_label)
        self.list_articoli = QtWidgets.QListWidget(self.centralwidget)
        self.list_articoli.setObjectName("list_articoli")
        self.ver_lay_list_articoli.addWidget(self.list_articoli)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.start_scarico_btn = QtWidgets.QPushButton(self.centralwidget)
        self.start_scarico_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.start_scarico_btn.setObjectName("start_scarico_btn")
        self.horizontalLayout.addWidget(self.start_scarico_btn)
        self.close_ordine_btn = QtWidgets.QPushButton(self.centralwidget)
        self.close_ordine_btn.setEnabled(False)
        self.close_ordine_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.close_ordine_btn.setObjectName("close_ordine_btn")
        self.horizontalLayout.addWidget(self.close_ordine_btn)
        self.ver_lay_list_articoli.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.ver_lay_list_articoli)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ordini_label.setText(_translate("MainWindow", "Ordini"))
        self.articoli_label.setText(_translate("MainWindow", "Articoli"))
        self.start_scarico_btn.setText(_translate("MainWindow", "Inizia Scarico"))
        self.close_ordine_btn.setText(_translate("MainWindow", "Chiudi Ordine"))
